# Proyecto Bases de Datos

#### Puntos extras, yupi!

## Parte 1 - Presentación (5 puntos)

Presenta tus resultados en una libreta de Jupyter de manera clara y concisa. 
Deberás explicar:
   - tu método de resolución
   - el algoritmo
   - las gráficas y/o DataFrame final
   - las conclusiones.

    ### Que voy a hacer?

       - Importar paqueteria cvs
       - Cargar base de datos
       - Revisar mis datos columna tras columna para analisar informacion
       - Limpiare mi base de datos haciendo una copia para no alterar mi base original
       - Analizare la informacion que me interese

In [2]:
# Importar librerias necesarias (no importa el orden)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#Ejecutar mi base de datos

In [4]:
# Cargar mi base de datos
OCDE=pd.read_csv('BLI.csv')

# Ver los env=cabezados de mi base
OCDE.head()

,LOCATION,Country,INDICATOR,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
0,AUS,Australia,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.3,NaN,NaN
1,AUT,Austria,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.7,NaN,NaN
2,BEL,Belgium,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.8,NaN,NaN
3,CAN,Canada,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,3.9,NaN,NaN
4,CZE,Czech Republic,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,1.8,NaN,NaN

## Parte 2 -  Preámbulo (5 puntos )

- Presenta todo lo necesario para comenzar tu análisis de la información.
- Todo deberá estar comentado para que el usuario final y puede ser entendido

    ### Que voy a hacer?

    - Buscar patrones 
    - Buscar relaciones
    - Cosas curiosas de los datos

    ### Que usare hoy ?

    - Usaremos pandas para el analisis
    - Usarems MATPLOTLIB.PYPLOT
    - Usaremos numpy (para manipular informacion: sumar, restar, dividir, multiplicar)

## Parte 3 - Análisis inicial (20 puntos)

### Presenta entrega el resultado y el código utilizado. Mientras más explícito, mejor. Mientras más bonito, mejor
 
- 3.1 ¿Cuántos países hay en la base de datos? ¿Cuáles son?
- 3.2 ¿Cuántos tipos de unidades se manejan? 
- 3.3 ¿Cuáles son los indicadores medidos? ¿Cuántos son? 
- 3.4 Descripción básica de los indicadores numéricos (estadística descriptiva) 
- 3.5 ¿Podemos eliminar algunas columnas de nuestra base de datos sin perder información importante? 
      Presenta la tabla y explica por qué eliminste dichas columnas
- 3.6 ¿Puedes cambiar en nombre de las columnas a español?

### 3.1 ¿Cuántos países hay en la base de datos? ¿Cuáles son?

In [24]:
#Numero de paises de mi base de datos OCDE e imprimir
num_paises=len(OCDE['Country'].unique())-1
print('Numero de paises de mi base de datos OCDE: ',num_paises)

Numero de paises de mi base de datos OCDE:  38

In [25]:
#Nombre de los paises de mi base de datos OCDE e imprimir
nombre_paises=OCDE['Country'].unique()
pd.DataFrame(nombre_paises)

                  0
0         Australia
1           Austria
2           Belgium
3            Canada
4    Czech Republic
5           Denmark
6           Finland
7            France
8           Germany
9            Greece
10          Hungary
11          Iceland
12          Ireland
13            Italy
14            Japan
15            Korea
16       Luxembourg
17           Mexico
18      Netherlands
19      New Zealand
20           Norway
21           Poland
22         Portugal
23  Slovak Republic
24            Spain
25           Sweden
26      Switzerland
27           Turkey
28   United Kingdom
29    United States
30           Brazil
31            Chile
32          Estonia
33           Israel
34           Latvia
35           Russia
36         Slovenia
37     South Africa
38     OECD - Total

### 3.2 Cuantos tipos de unidades se manejan?

In [26]:
# Llamo las unidades de mi base
tipos_de_unidades=(OCDE['Unit'].unique())
pd.DataFrame(tipos_de_unidades)

                            0
0                  Percentage
1               Average score
2                       Ratio
3                   US Dollar
4                       Years
5  Micrograms per cubic metre
6                       Hours

### 3.3 ¿Cuáles son los indicadores medidos? ¿Cuántos son?

In [27]:
# Llamar los indicadores de mi base
indicadores=(OCDE['Indicator'].unique())
pd.DataFrame(indicadores)

                                                    0
0                            Labour market insecurity
1   Stakeholder engagement for developing regulations
2                 Feeling safe walking alone at night
3                  Dwellings without basic facilities
4                                 Housing expenditure
5                                    Rooms per person
6            Household net adjusted disposable income
7                      Household net financial wealth
8                                     Employment rate
9                         Long-term unemployment rate
10                                  Personal earnings
11                         Quality of support network
12                             Educational attainment
13                                     Student skills
14                                 Years in education
15                                      Air pollution
16                                      Water quality
17                                      Voter turnout
18                                    Life expectancy
19                               Self-reported health
20                                  Life satisfaction
21                                      Homicide rate
22                  Employees working very long hours
23          Time devoted to leisure and personal care

In [13]:
num_indicadores=len(OCDE['Indicator'].unique())
print(num_indicadores)

24

 ## 3.4 Descripción básica de los indicadores numéricos (estadística descriptiva)

In [28]:
# Descripción básica de los indicadores numéricos (estadística descriptiva)
OCDE.describe()

       PowerCode Code  Reference Period Code  Reference Period          Value
count          3398.0                    0.0               0.0    3398.000000
mean              0.0                    NaN               NaN    5353.200309
std               0.0                    NaN               NaN   15832.099269
min               0.0                    NaN               NaN       0.000000
25%               0.0                    NaN               NaN       7.000000
50%               0.0                    NaN               NaN      62.000000
75%               0.0                    NaN               NaN      91.000000
max               0.0                    NaN               NaN  176076.000000

### 3.5 ¿Podemos eliminar algunas columnas de nuestra base de datos sin perder información importante?
          Presenta la tabla y explica por qué eliminste dichas columnas

In [29]:
# ¿Podemos eliminar algunas columnas de nuestra base de datos sin perder información importante? 
# Si podemos

#Creamos una nueva base de datos y eliminamos algunas columnas
OCDE2=OCDE.drop(['MEASURE','INEQUALITY','Unit Code','PowerCode Code','Reference Period Code','Flag Codes','Flags'], axis=1)

In [30]:
pd.DataFrame(OCDE2)

# Esta tabla ya esta mas limpia y puedo ver la informacion que realmente me interesa.

,LOCATION,Country,INDICATOR,Indicator,Measure,Inequality,Unit,PowerCode,Reference Period,Value
0,AUS,Australia,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,4.30
1,AUT,Austria,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.70
2,BEL,Belgium,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,4.80
3,CAN,Canada,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,3.90
4,CZE,Czech Republic,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,1.80
5,DNK,Denmark,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.30
6,FIN,Finland,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.70
7,FRA,France,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,5.00
8,DEU,Germany,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.00
9,GRC,Greece,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,17.40
10,HUN,Hungary,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,4.80
11,ISL,Iceland,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.60
12,IRL,Ireland,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.10
13,ITA,Italy,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,8.10
14,JPN,Japan,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,1.50
15,KOR,Korea,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.40
16,LUX,Luxembourg,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,3.20
17,MEX,Mexico,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,4.60
18,NLD,Netherlands,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.10
19,NZL,New Zealand,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,4.90
20,NOR,Norway,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.70
21,POL,Poland,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,4.30
22,PRT,Portugal,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,6.50
23,SVK,Slovak Republic,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,6.70
24,ESP,Spain,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,17.30
25,SWE,Sweden,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,5.70
26,CHE,Switzerland,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,1.80
27,TUR,Turkey,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,13.00
28,GBR,United Kingdom,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.60
29,USA,United States,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,3.80
...,...,...,...,...,...,...,...,...,...,...
3368,GRC,Greece,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.42
3369,HUN,Hungary,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.82
3370,ISL,Iceland,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,13.87
3371,IRL,Ireland,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,15.06
3372,ITA,Italy,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.29
3373,JPN,Japan,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.53
3374,KOR,Korea,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.00
3375,LUX,Luxembourg,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.92
3376,MEX,Mexico,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,12.39
3377,NLD,Netherlands,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,15.71
3378,NZL,New Zealand,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.95
3379,NOR,Norway,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,15.65
3380,POL,Poland,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.08
3381,PRT,Portugal,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.64
3382,SVK,Slovak Republic,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.77
3383,ESP,Spain,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,15.48
3384,SWE,Sweden,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,15.23
3385,CHE,Switzerland,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.78
3386,TUR,Turkey,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,12.22
3387,GBR,United Kingdom,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.86
3388,USA,United States,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.39
3389,BRA,Brazil,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.18
3390,CHL,Chile,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.66
3391,EST,Estonia,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.43
3392,ISR,Israel,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,13.63
3393,LVA,Latvia,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,13.45
3394,RUS,Russia,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.66
3395,SVN,Slovenia,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.17
3396,ZAF,South Africa,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.37
3397,OECD,OECD - Total,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.60

### 3.6 ¿Puedes cambiar en nombre de las columnas a español?

In [36]:
OCDE2.rename(columns={'LOCATION':'LOCACION','Country':'Pais','INDICATOR':'INDICADOR','Indicator':'Indicador','Measure':'Medida','Inequality':'Genero','Unit':'Unidad','PowerCode':'Codigo','Reference Period':'Periodo','Value':'Valor'})

,LOCACION,Pais,INDICADOR,Indicador,Medida,Genero,Unidad,Codigo,Periodo,Valor
0,AUS,Australia,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,4.30
1,AUT,Austria,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.70
2,BEL,Belgium,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,4.80
3,CAN,Canada,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,3.90
4,CZE,Czech Republic,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,1.80
5,DNK,Denmark,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.30
6,FIN,Finland,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.70
7,FRA,France,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,5.00
8,DEU,Germany,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.00
9,GRC,Greece,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,17.40
10,HUN,Hungary,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,4.80
11,ISL,Iceland,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.60
12,IRL,Ireland,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.10
13,ITA,Italy,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,8.10
14,JPN,Japan,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,1.50
15,KOR,Korea,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.40
16,LUX,Luxembourg,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,3.20
17,MEX,Mexico,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,4.60
18,NLD,Netherlands,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.10
19,NZL,New Zealand,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,4.90
20,NOR,Norway,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.70
21,POL,Poland,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,4.30
22,PRT,Portugal,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,6.50
23,SVK,Slovak Republic,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,6.70
24,ESP,Spain,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,17.30
25,SWE,Sweden,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,5.70
26,CHE,Switzerland,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,1.80
27,TUR,Turkey,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,13.00
28,GBR,United Kingdom,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.60
29,USA,United States,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,3.80
...,...,...,...,...,...,...,...,...,...,...
3368,GRC,Greece,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.42
3369,HUN,Hungary,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.82
3370,ISL,Iceland,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,13.87
3371,IRL,Ireland,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,15.06
3372,ITA,Italy,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.29
3373,JPN,Japan,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.53
3374,KOR,Korea,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.00
3375,LUX,Luxembourg,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.92
3376,MEX,Mexico,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,12.39
3377,NLD,Netherlands,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,15.71
3378,NZL,New Zealand,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.95
3379,NOR,Norway,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,15.65
3380,POL,Poland,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.08
3381,PRT,Portugal,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.64
3382,SVK,Slovak Republic,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.77
3383,ESP,Spain,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,15.48
3384,SWE,Sweden,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,15.23
3385,CHE,Switzerland,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.78
3386,TUR,Turkey,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,12.22
3387,GBR,United Kingdom,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.86
3388,USA,United States,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.39
3389,BRA,Brazil,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.18
3390,CHL,Chile,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.66
3391,EST,Estonia,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.43
3392,ISR,Israel,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,13.63
3393,LVA,Latvia,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,13.45
3394,RUS,Russia,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.66
3395,SVN,Slovenia,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.17
3396,ZAF,South Africa,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.37
3397,OECD,OECD - Total,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.60

## Parte 4 - Búsqueda de datos (30 puntos)

In [ ]:
Imprime el los datos o Dataframes ( ¡Panditas! :D ) que se te solicitan (Recuerden no modificar el original) 
y entregenme sus observacioens de los datos (pueden usar gráficas
 
    - 4.1 Imprime los valores de los indicadores para México, eliminando la columna del país) 
    - 4.2 Muestra los países con esperanza de vida femenina mayor al promedio general y sus datos 
    - 4.3 Muestra los países cuya seguridad al caminar en la noche es menor al promedio y sus valores 
    - 4.4 Muestra las columnas de los datos completos de los países con mejor satisfacción de vida.

### 4.1 Imprime los valores de los indicadores para México, eliminando la columna del país)

In [6]:
# Aqui estoy creando un nuevo panda para modificar y eliminar columnas
OCDE2=OCDE.set_index('LOCATION')
pd.DataFrame(OCDE2)

,Country,INDICATOR,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
LOCATION,,,,,,,,,,,,,,,,
AUS,Australia,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.30,NaN,NaN
AUT,Austria,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.70,NaN,NaN
BEL,Belgium,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.80,NaN,NaN
CAN,Canada,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,3.90,NaN,NaN
CZE,Czech Republic,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,1.80,NaN,NaN
DNK,Denmark,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.30,NaN,NaN
FIN,Finland,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.70,NaN,NaN
FRA,France,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,5.00,NaN,NaN
DEU,Germany,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.00,NaN,NaN
GRC,Greece,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,17.40,NaN,NaN
HUN,Hungary,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.80,NaN,NaN
ISL,Iceland,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.60,NaN,NaN
IRL,Ireland,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.10,NaN,NaN
ITA,Italy,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,8.10,NaN,NaN
JPN,Japan,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,1.50,NaN,NaN
KOR,Korea,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.40,NaN,NaN
LUX,Luxembourg,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,3.20,NaN,NaN
MEX,Mexico,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.60,NaN,NaN
NLD,Netherlands,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.10,NaN,NaN
NZL,New Zealand,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.90,NaN,NaN
NOR,Norway,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.70,NaN,NaN
POL,Poland,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.30,NaN,NaN
PRT,Portugal,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,6.50,NaN,NaN
SVK,Slovak Republic,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,6.70,NaN,NaN
ESP,Spain,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,17.30,NaN,NaN
SWE,Sweden,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,5.70,NaN,NaN
CHE,Switzerland,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,1.80,NaN,NaN
TUR,Turkey,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,13.00,NaN,NaN
GBR,United Kingdom,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.60,NaN,NaN
USA,United States,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,3.80,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
GRC,Greece,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.42,E,Estimated value
HUN,Hungary,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.82,E,Estimated value
ISL,Iceland,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,13.87,E,Estimated value
IRL,Ireland,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,15.06,E,Estimated value
ITA,Italy,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.29,NaN,NaN
JPN,Japan,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.53,NaN,NaN
KOR,Korea,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.00,NaN,NaN
LUX,Luxembourg,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.92,E,Estimated value
MEX,Mexico,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,12.39,E,Estimated value
NLD,Netherlands,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,15.71,E,Estimated value
NZL,New Zealand,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.95,NaN,NaN
NOR,Norway,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,15.65,NaN,NaN
POL,Poland,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.08,NaN,NaN
PRT,Portugal,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.64,E,Estimated value
SVK,Slovak Republic,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.77,E,Estimated value
ESP,Spain,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,15.48,NaN,NaN
SWE,Sweden,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,15.23,NaN,NaN
CHE,Switzerland,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.78,E,Estimated value
TUR,Turkey,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,12.22,E,Estimated value
GBR,United Kingdom,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.86,NaN,NaN
USA,United States,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.39,NaN,NaN
BRA,Brazil,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.18,E,Estimated value
CHL,Chile,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.66,E,Estimated value
EST,Estonia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.43,NaN,NaN
ISR,Israel,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,13.63,E,Estimated value
LVA,Latvia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,13.45,NaN,NaN
RUS,Russia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.66,E,Estimated value
SVN,Slovenia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.17,NaN,NaN
ZAF,South Africa,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.37,NaN,NaN
OECD,OECD - Total,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.60,NaN,NaN

In [7]:
# BORRO LA COLUMNA COUNTRY
OCDE3=OCDE2.drop(['Country'], axis=1)

In [8]:
pd.DataFrame(OCDE3)

,INDICATOR,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
LOCATION,,,,,,,,,,,,,,,
AUS,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.30,NaN,NaN
AUT,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.70,NaN,NaN
BEL,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.80,NaN,NaN
CAN,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,3.90,NaN,NaN
CZE,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,1.80,NaN,NaN
DNK,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.30,NaN,NaN
FIN,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.70,NaN,NaN
FRA,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,5.00,NaN,NaN
DEU,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.00,NaN,NaN
GRC,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,17.40,NaN,NaN
HUN,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.80,NaN,NaN
ISL,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.60,NaN,NaN
IRL,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.10,NaN,NaN
ITA,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,8.10,NaN,NaN
JPN,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,1.50,NaN,NaN
KOR,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.40,NaN,NaN
LUX,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,3.20,NaN,NaN
MEX,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.60,NaN,NaN
NLD,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.10,NaN,NaN
NZL,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.90,NaN,NaN
NOR,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.70,NaN,NaN
POL,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.30,NaN,NaN
PRT,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,6.50,NaN,NaN
SVK,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,6.70,NaN,NaN
ESP,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,17.30,NaN,NaN
SWE,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,5.70,NaN,NaN
CHE,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,1.80,NaN,NaN
TUR,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,13.00,NaN,NaN
GBR,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.60,NaN,NaN
USA,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,3.80,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
GRC,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.42,E,Estimated value
HUN,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.82,E,Estimated value
ISL,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,13.87,E,Estimated value
IRL,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,15.06,E,Estimated value
ITA,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.29,NaN,NaN
JPN,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.53,NaN,NaN
KOR,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.00,NaN,NaN
LUX,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.92,E,Estimated value
MEX,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,12.39,E,Estimated value
NLD,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,15.71,E,Estimated value
NZL,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.95,NaN,NaN
NOR,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,15.65,NaN,NaN
POL,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.08,NaN,NaN
PRT,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.64,E,Estimated value
SVK,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.77,E,Estimated value
ESP,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,15.48,NaN,NaN
SWE,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,15.23,NaN,NaN
CHE,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.78,E,Estimated value
TUR,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,12.22,E,Estimated value
GBR,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.86,NaN,NaN
USA,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.39,NaN,NaN
BRA,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.18,E,Estimated value
CHL,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.66,E,Estimated value
EST,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.43,NaN,NaN
ISR,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,13.63,E,Estimated value
LVA,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,13.45,NaN,NaN
RUS,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.66,E,Estimated value
SVN,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.17,NaN,NaN
ZAF,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.37,NaN,NaN
OECD,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.60,NaN,NaN

In [9]:
MEXICO=OCDE3.loc['MEX']
MEXICO.head()

,INDICATOR,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
LOCATION,,,,,,,,,,,,,,,
MEX,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.6,NaN,NaN
MEX,CG_SENG,Stakeholder engagement for developing regulations,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,3.5,NaN,NaN
MEX,CG_SENG,Stakeholder engagement for developing regulations,L,Value,MN,Men,AVSCORE,Average score,0,Units,NaN,NaN,3.5,E,Estimated value
MEX,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,Women,AVSCORE,Average score,0,Units,NaN,NaN,3.5,E,Estimated value
MEX,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,45.9,NaN,NaN

### 4.2 Muestra los países c/esperanza de vida femenina > al promedio general y sus datos

In [10]:
# Creo una nueva base de datos
Expectativa_de_vida=OCDE

In [11]:
# Llamo la columna Inequality que me muestra hombre, mujer y total
Indice_Expectativa=Expectativa_de_vida.set_index('Inequality')
Indice_Expectativa

,LOCATION,Country,INDICATOR,Indicator,MEASURE,Measure,INEQUALITY,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
Inequality,,,,,,,,,,,,,,,,
Total,AUS,Australia,JE_LMIS,Labour market insecurity,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,4.30,NaN,NaN
Total,AUT,Austria,JE_LMIS,Labour market insecurity,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,2.70,NaN,NaN
Total,BEL,Belgium,JE_LMIS,Labour market insecurity,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,4.80,NaN,NaN
Total,CAN,Canada,JE_LMIS,Labour market insecurity,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,3.90,NaN,NaN
Total,CZE,Czech Republic,JE_LMIS,Labour market insecurity,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,1.80,NaN,NaN
Total,DNK,Denmark,JE_LMIS,Labour market insecurity,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,2.30,NaN,NaN
Total,FIN,Finland,JE_LMIS,Labour market insecurity,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,2.70,NaN,NaN
Total,FRA,France,JE_LMIS,Labour market insecurity,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,5.00,NaN,NaN
Total,DEU,Germany,JE_LMIS,Labour market insecurity,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,2.00,NaN,NaN
Total,GRC,Greece,JE_LMIS,Labour market insecurity,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,17.40,NaN,NaN
Total,HUN,Hungary,JE_LMIS,Labour market insecurity,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,4.80,NaN,NaN
Total,ISL,Iceland,JE_LMIS,Labour market insecurity,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,2.60,NaN,NaN
Total,IRL,Ireland,JE_LMIS,Labour market insecurity,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,2.10,NaN,NaN
Total,ITA,Italy,JE_LMIS,Labour market insecurity,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,8.10,NaN,NaN
Total,JPN,Japan,JE_LMIS,Labour market insecurity,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,1.50,NaN,NaN
Total,KOR,Korea,JE_LMIS,Labour market insecurity,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,2.40,NaN,NaN
Total,LUX,Luxembourg,JE_LMIS,Labour market insecurity,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,3.20,NaN,NaN
Total,MEX,Mexico,JE_LMIS,Labour market insecurity,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,4.60,NaN,NaN
Total,NLD,Netherlands,JE_LMIS,Labour market insecurity,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,2.10,NaN,NaN
Total,NZL,New Zealand,JE_LMIS,Labour market insecurity,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,4.90,NaN,NaN
Total,NOR,Norway,JE_LMIS,Labour market insecurity,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,2.70,NaN,NaN
Total,POL,Poland,JE_LMIS,Labour market insecurity,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,4.30,NaN,NaN
Total,PRT,Portugal,JE_LMIS,Labour market insecurity,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,6.50,NaN,NaN
Total,SVK,Slovak Republic,JE_LMIS,Labour market insecurity,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,6.70,NaN,NaN
Total,ESP,Spain,JE_LMIS,Labour market insecurity,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,17.30,NaN,NaN
Total,SWE,Sweden,JE_LMIS,Labour market insecurity,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,5.70,NaN,NaN
Total,CHE,Switzerland,JE_LMIS,Labour market insecurity,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,1.80,NaN,NaN
Total,TUR,Turkey,JE_LMIS,Labour market insecurity,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,13.00,NaN,NaN
Total,GBR,United Kingdom,JE_LMIS,Labour market insecurity,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,2.60,NaN,NaN
Total,USA,United States,JE_LMIS,Labour market insecurity,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,3.80,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Women,GRC,Greece,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.42,E,Estimated value
Women,HUN,Hungary,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.82,E,Estimated value
Women,ISL,Iceland,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,13.87,E,Estimated value
Women,IRL,Ireland,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,15.06,E,Estimated value
Women,ITA,Italy,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.29,NaN,NaN
Women,JPN,Japan,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.53,NaN,NaN
Women,KOR,Korea,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.00,NaN,NaN
Women,LUX,Luxembourg,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.92,E,Estimated value
Women,MEX,Mexico,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,12.39,E,Estimated value
Women,NLD,Netherlands,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,15.71,E,Estimated value
Women,NZL,New Zealand,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.95,NaN,NaN
Women,NOR,Norway,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,15.65,NaN,NaN
Women,POL,Poland,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.08,NaN,NaN
Women,PRT,Portugal,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.64,E,Estimated value
Women,SVK,Slovak Republic,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.77,E,Estimated value
Women,ESP,Spain,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,15.48,NaN,NaN
Women,SWE,Sweden,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,15.23,NaN,NaN
Women,CHE,Switzerland,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.78,E,Estimated value
Women,TUR,Turkey,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,12.22,E,Estimated value
Women,GBR,United Kingdom,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.86,NaN,NaN
Women,USA,United States,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.39,NaN,NaN
Women,BRA,Brazil,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.18,E,Estimated value
Women,CHL,Chile,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.66,E,Estimated value
Women,EST,Estonia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.43,NaN,NaN
Women,ISR,Israel,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,13.63,E,Estimated value
Women,LVA,Latvia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,13.45,NaN,NaN
Women,RUS,Russia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.66,E,Estimated value
Women,SVN,Slovenia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.17,NaN,NaN
Women,ZAF,South Africa,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.37,NaN,NaN
Women,OECD,OECD - Total,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.60,NaN,NaN

In [12]:
# llamo unicamente las filas WOMAN
Indice_Expectativa_Mujer=Indice_Expectativa.loc['Women']

In [81]:
Indice_Expectativa_Mujer

,LOCATION,Country,INDICATOR,Indicator,MEASURE,Measure,INEQUALITY,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
Inequality,,,,,,,,,,,,,,,,
Women,AUS,Australia,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,AVSCORE,Average score,0,Units,NaN,NaN,2.70,E,Estimated value
Women,AUT,Austria,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,AVSCORE,Average score,0,Units,NaN,NaN,1.30,E,Estimated value
Women,BEL,Belgium,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,AVSCORE,Average score,0,Units,NaN,NaN,2.20,E,Estimated value
Women,CAN,Canada,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,AVSCORE,Average score,0,Units,NaN,NaN,3.00,E,Estimated value
Women,CZE,Czech Republic,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,AVSCORE,Average score,0,Units,NaN,NaN,2.60,E,Estimated value
Women,DNK,Denmark,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,AVSCORE,Average score,0,Units,NaN,NaN,2.10,E,Estimated value
Women,FIN,Finland,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,AVSCORE,Average score,0,Units,NaN,NaN,2.30,E,Estimated value
Women,FRA,France,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,AVSCORE,Average score,0,Units,NaN,NaN,2.10,E,Estimated value
Women,DEU,Germany,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,AVSCORE,Average score,0,Units,NaN,NaN,2.10,E,Estimated value
Women,GRC,Greece,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,AVSCORE,Average score,0,Units,NaN,NaN,1.90,E,Estimated value
Women,HUN,Hungary,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,AVSCORE,Average score,0,Units,NaN,NaN,1.20,E,Estimated value
Women,ISL,Iceland,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,AVSCORE,Average score,0,Units,NaN,NaN,1.60,E,Estimated value
Women,IRL,Ireland,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,AVSCORE,Average score,0,Units,NaN,NaN,0.80,E,Estimated value
Women,ITA,Italy,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,AVSCORE,Average score,0,Units,NaN,NaN,1.50,E,Estimated value
Women,JPN,Japan,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,AVSCORE,Average score,0,Units,NaN,NaN,1.30,E,Estimated value
Women,KOR,Korea,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,AVSCORE,Average score,0,Units,NaN,NaN,2.40,E,Estimated value
Women,LUX,Luxembourg,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,AVSCORE,Average score,0,Units,NaN,NaN,1.50,E,Estimated value
Women,MEX,Mexico,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,AVSCORE,Average score,0,Units,NaN,NaN,3.50,E,Estimated value
Women,NLD,Netherlands,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,AVSCORE,Average score,0,Units,NaN,NaN,1.30,E,Estimated value
Women,NZL,New Zealand,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,AVSCORE,Average score,0,Units,NaN,NaN,2.50,E,Estimated value
Women,NOR,Norway,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,AVSCORE,Average score,0,Units,NaN,NaN,1.90,E,Estimated value
Women,POL,Poland,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,AVSCORE,Average score,0,Units,NaN,NaN,2.60,E,Estimated value
Women,PRT,Portugal,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,AVSCORE,Average score,0,Units,NaN,NaN,1.20,E,Estimated value
Women,SVK,Slovak Republic,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,AVSCORE,Average score,0,Units,NaN,NaN,2.90,E,Estimated value
Women,ESP,Spain,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,AVSCORE,Average score,0,Units,NaN,NaN,1.60,E,Estimated value
Women,SWE,Sweden,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,AVSCORE,Average score,0,Units,NaN,NaN,2.00,E,Estimated value
Women,CHE,Switzerland,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,AVSCORE,Average score,0,Units,NaN,NaN,2.60,E,Estimated value
Women,TUR,Turkey,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,AVSCORE,Average score,0,Units,NaN,NaN,2.10,E,Estimated value
Women,GBR,United Kingdom,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,AVSCORE,Average score,0,Units,NaN,NaN,2.90,E,Estimated value
Women,USA,United States,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,AVSCORE,Average score,0,Units,NaN,NaN,3.20,E,Estimated value
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Women,GRC,Greece,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.42,E,Estimated value
Women,HUN,Hungary,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.82,E,Estimated value
Women,ISL,Iceland,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,13.87,E,Estimated value
Women,IRL,Ireland,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,15.06,E,Estimated value
Women,ITA,Italy,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.29,NaN,NaN
Women,JPN,Japan,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.53,NaN,NaN
Women,KOR,Korea,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.00,NaN,NaN
Women,LUX,Luxembourg,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.92,E,Estimated value
Women,MEX,Mexico,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,12.39,E,Estimated value
Women,NLD,Netherlands,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,15.71,E,Estimated value
Women,NZL,New Zealand,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.95,NaN,NaN
Women,NOR,Norway,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,15.65,NaN,NaN
Women,POL,Poland,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.08,NaN,NaN
Women,PRT,Portugal,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.64,E,Estimated value
Women,SVK,Slovak Republic,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.77,E,Estimated value
Women,ESP,Spain,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,15.48,NaN,NaN
Women,SWE,Sweden,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,15.23,NaN,NaN
Women,CHE,Switzerland,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.78,E,Estimated value
Women,TUR,Turkey,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,12.22,E,Estimated value
Women,GBR,United Kingdom,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.86,NaN,NaN
Women,USA,United States,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.39,NaN,NaN
Women,BRA,Brazil,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.18,E,Estimated value
Women,CHL,Chile,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.66,E,Estimated value
Women,EST,Estonia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.43,NaN,NaN
Women,ISR,Israel,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,13.63,E,Estimated value
Women,LVA,Latvia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,13.45,NaN,NaN
Women,RUS,Russia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.66,E,Estimated value
Women,SVN,Slovenia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.17,NaN,NaN
Women,ZAF,South Africa,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.37,NaN,NaN
Women,OECD,OECD - Total,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,HOUR,Hours,0,Units,NaN,NaN,14.60,NaN,NaN

In [21]:

#Aqui saco el numero de registros de mujeres
num_woman=len(Indice_Expectativa_Mujer)
print('Numero de mujeres de mi base: ',num_woman)

prom_num_woman=np.mean(Indice_Expectativa_Mujer['Value'])
print('Promedio de expectativa de vida de mujeres: ',prom_num_woman)

Numero de mujeres de mi base:  890
Promedio de expectativa de vida de mujeres:  4692.162977528093

In [ ]:

MARISSA:


valores_mujer = mujeres_expectativa['Value']
## Pregunta cuáles países tienen expectativa de vida mayor al promedio

#Parámetro de filtro = ['Value']restricción
promedio_vida=82.24
total=valores_mujer.count()

P_V = sum(valores_mujer>promedio_vida)
p_promedio = P_V/total

print("Existen ", P_V, " países con expectativa mayor al promedio", "de un total de ", total)
print("Esto representa el ", round(p_promedio,4)*100, "% del total de la muestra, según un parámetro promedio_vida= ",promedio_vida)

In [ ]:
MARISSA:

#Para conocer cuáles países son los de mejor esperanza de vida (arriba del promedio)
#mujeres_expectativa=mujeres_expectativa.drop(["MEASURE", "INEQUALITY","Unit Code","PowerCode Code","Reference Period Code","Flag Codes","Flags"],axis=1)
Expectativa_arriba_media = mujeres_expectativa[mujeres_expectativa['Value'] > 82.24 ]
#Puedo acomodar el set de datos, de mayor a menor expectativa... 
Expectativa_arriba_sorteada=Expectativa_arriba_media.sort_values(by=['Value'],axis=0,ascending=False)
pd.DataFrame(Expectativa_arriba_sorteada)

In [ ]:
### Parte 5 - Información gráfica (40 puntos + 20 puntos extra)

Entrega la gráficas con títulos, nombres en los ejes y mejora la presentación de las mismas (colores, número de cajas en el histograma, valores extra) . Así mismo deberán entregar la interpretación de las mismas. 

- Realiza 3 análisis de la relación entre dos variables. 

- Realizar 2 análisis donde se necesite usar histogramas. 

- Presenta un análisis utilizando una gráfica de barras de los indicadores para múltiples paises. (PUNTOS EXTRA) 

- Realicen una análisis de correlación para 4 variables (PUNTOS EXTRA) (¿Scatter or density?)

### Parte 6 - Referencias para la tarea: 

- http://benalexkeen.com/correlation-in-python/
- https://github.com/jakevdp/PythonDataScienceHandbook/tree/be23269c7eb119e093a6d5ce91e464f5e686d9ab/notebooks
- https://machinelearningmastery.com/visualize-machine-learning-data-python-pandas/